# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9ea985b3-b888-4010-9f20-7aef3a56f608";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9ea985b3-b888-4010-9f20-7aef3a56f608".device = "/dev/disk/by-uuid/9ea985b3-b888-4010-9f20-7aef3a56f608";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2FF9-4FB9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a16834c9-7b48-43dc-b138-40cca1713939"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
