# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-cfc6a939-4f0f-4154-9520-77aca09605d6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cfc6a939-4f0f-4154-9520-77aca09605d6".device = "/dev/disk/by-uuid/cfc6a939-4f0f-4154-9520-77aca09605d6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2E13-0842";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-126147a9-5d31-446f-8f33-8f0ea8633d18"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
